trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: get-digital-business

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build job
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

    - publish: '$(Build.SourcesDirectory)/build'
      artifact: 'drop'
      displayName: 'Publish Artifact'

- stage: Dev
  displayName: Development stage
  jobs:
  - job: DeployDev
    displayName: Deploy to dev
    steps:
    - download: current
      artifact: drop
      displayName: 'Download Build Artifacts'

    - task: AzureStaticWebApp@0
      inputs:
        app_location: '/'
        output_location: '/'
        azure_static_web_apps_api_token: $(deploymentToken)
        deployment_environment: 'dev'
        production_branch: 'main'

- stage: Prod
  displayName: Production stage
  dependsOn: Dev
  jobs:
  - deployment: DeployProd
    displayName: Deploy to production
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
            displayName: 'Download Build Artifacts'

          - task: AzureStaticWebApp@0
            inputs:
              app_location: '/'
              output_location: '/'
              azure_static_web_apps_api_token: $(deploymentToken)
              deployment_environment: 'Production'
              production_branch: 'main'
    # Manual approval required before deployment to production
    condition: succeeded()
    timeoutInMinutes: 1440 # Timeout for manual approval
